pull_request_rules:
  # membuat requirement dari automerge dengan sistem
  # ketika workflow build passed maka akan dicentang
  # ketika target pull request ke main maka akan dicentang
  # ketika dikasih label 'ready-to-merge' akan dicentang

  # ketika requirement telah terpenuhi maka bot akan bekerja
  # dan pull request secara otomatis akan merge
  - name: ci testing kalo sukses ke squash dengan label
    conditions:
      - check-success=build
      - base=main
      - label=ready-to-merge
    actions:
      # menambahkan komentar jika sudah di merge
      comment:
        message: terima kasih atas kontribusinya @{{author}}!
      # menambahkan label jika sudah di merge
      label:
        add:
            - sudah direview!
      # metode sistem dari automerge
      merge:
        method: squash

  # membuat label dengan kondisi jika di dalam pull request
  # terdapat file java
  - name: java label
    conditions:
      - files~=\.java$
    actions:
      # menabahkan label 'java files'
      # dan lebel 'request tim java untuk review'
      label:
        add:
          - java files
          - request tim java untuk review

  # membuat label dengan kondisi jika di dalam pull request
  # terdapat file markdown
  - name: markdown label
    conditions:
      - files~=\.md$
    actions:
      #  menambahkan label 'markdown files'
      label:
        add:
          - markdown files

  # membuat sistem bot me mention java team untuk meriview
  # dari pull request dengan kondisi jika terdapat file java
  - name: request java team untuk review
    conditions:
      - label=java files
    actions:
      request_reviews:
        teams:
          - "@bellshade/java-team"
